# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Get current timestamp
      id: timestamp
      run: export tstamp="$(date +%Y-%m-%d_%H%M)";pwd;echo "tstamp is "$tstamp; echo "tstamp=$tstamp" >> $GITHUB_OUTPUT
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        # run previously failed tests first, generate HTML report with sll styles inside it
        export tstamp=${{steps.timestamp.outputs.tstamp}}
        echo "tstamp is "$tstamp
        pytest --ff ./test_sample.py --cache-clear  --html=test_sample_report_$tstamp.htm --self-contained-html
    - name: save report
      uses: actions/upload-artifact@v4
      with:
        name: test_sample_report_${{steps.timestamp.outputs.tstamp}}.htm
        path: test_sample_report_${{steps.timestamp.outputs.tstamp}}.htm
    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        allure_history: allure-history
        allure_results: build/allure-results
